spring:
  application:
    name: rabbitmq-spring-amqp

  docker:
    compose:
      file: rabbit/rabbitmq-spring-amqp/compose.yaml

  profiles:
    active: usage_message

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000